/**
 * «فرصة مكافأة»: a student who is short of the chapter's opportunity limit
 * earns one opportunity back for every two consecutive passing exams.
 *
 * The rule is fixed (no settings):
 * - A pass is a score at or above the exam's own pass mark (final exams too).
 * - A score between the discount mark and the pass mark breaks the streak
 *   without a deduction; an absence or a discount score is a loss and also
 *   breaks it.
 * - Leave, grace, «بدون خصم» exams, unavailable exams, settled/excluded grades
 *   and exams before registration are neutral: they neither count nor break.
 * - Everything below the limit is recoverable except what an administrator
 *   removed by hand (manual or bulk deduction, or what a reset took off the
 *   balance it found), less what a later reset gave back. A gap from raising
 *   the limit is recoverable.
 * - At most two bonuses per chapter, never above the limit, never for a
 *   dismissed student.
 * - Only exams dated on/after BONUS_START_DAY count as passes, and only from
 *   the balance's opening: an exam on the day of a return or a reset counts
 *   unless that return or reset settled its grade.
 * - A pass counts on its exam's day, however late it or anything else that
 *   day is entered, and a day's exams count in exam order.
 * - A missing grade for an exam between the two passes holds the bonus until
 *   it is recorded, or until a later pair with nothing missing between its
 *   two passes earns it; one before the first pass does not.
 *
 * The bonus is an automatic ledger row regenerated by every academic replay,
 * exactly like «خصم تلقائي», so any grade or exam correction recomputes it.
 */
export const BONUS_OPPORTUNITY_ACTION = "فرصة مكافأة";
export const BONUS_PASSES_REQUIRED = 2;
export const BONUS_LIMIT_PER_CHAPTER = 2;
/** Baghdad day the rule started. Earlier exams never count as passes. */
export const BONUS_START_DAY = "2026-10-03";

/** Progress stored on the student: 0 none, 1 one pass counted, 2 earned but
 * held until a missing grade inside the streak is recorded or a later clean
 * pair earns it. */
export const BONUS_PROGRESS_WAITING = 2;

export function isBonusOpportunityLog(log: { action?: unknown } | null | undefined): boolean {
  return String(log?.action ?? "").trim() === BONUS_OPPORTUNITY_ACTION;
}

/** Ledger credits a person reads as «+»: manual additions, reactivation
 * balances and bonuses. */
export function isOpportunityCreditAction(action: unknown): boolean {
  const value = String(action ?? "").trim();
  return value === "إضافة" || value === "رصيد بعد تعهد" ||
    value === "رصيد إعادة التفعيل" || value === BONUS_OPPORTUNITY_ACTION;
}

export function bonusProgressLabel(
  progress: number | null | undefined,
  waitingExamName?: string | null,
): string {
  if (progress === BONUS_PROGRESS_WAITING) {
    return waitingExamName
      ? `${BONUS_OPPORTUNITY_ACTION} مستحقة، تنتظر درجة «${waitingExamName}»`
      : `${BONUS_OPPORTUNITY_ACTION} مستحقة، تنتظر درجة ناقصة`;
  }
  if (progress === 1) return `نجاح 1 من ${BONUS_PASSES_REQUIRED} نحو ${BONUS_OPPORTUNITY_ACTION}`;
  return "";
}
