import { createHash } from "node:crypto";
import type { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { baghdadDateKey } from "@/lib/baghdad-time";
import { normalizeGracePeriodRanges, type GracePeriodRange } from "@/lib/grace-periods";
import { loadActiveGracePeriodsByStudent } from "@/lib/grace-periods-server";

type PrismaClientLike = typeof db | Prisma.TransactionClient;

function dayKey(value: Date | string): string {
  return baghdadDateKey(value);
}

/**
 * Fingerprints every database input read by the academic recalculation engine.
 * A save must present the token generated by its latest preview; any grade,
 * leave, note, exam, opportunity, chapter, or student-state change invalidates
 * that preview instead of silently applying a different result.
 */
export async function buildStudentAcademicImpactToken(
  client: PrismaClientLike,
  input: {
    studentId: string;
    proposedCreatedAt?: Date | string;
    /** Proposed active grace periods of a grace-management change. */
    proposedGracePeriods?: GracePeriodRange[];
  },
): Promise<string> {
  const student = await client.student.findUnique({
    where: { id: input.studentId },
    select: {
      id: true,
      courseId: true,
      mainSite: true,
      subSite: true,
      locationScope: true,
      status: true,
      opportunities: true,
      baseOpportunities: true,
      createdAt: true,
      dismissalReason: true,
      dismissalNotes: true,
    },
  });

  const [
    grades,
    leaves,
    opportunityLogs,
    studentNotes,
    exams,
    courseLinks,
    chapters,
    gracePeriodsByStudent,
  ] = await Promise.all([
    client.grade.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        examId: true,
        status: true,
        score: true,
        notes: true,
        academicEffectExcluded: true,
        academicEffectExclusionReason: true,
        academicEffectExclusionSource: true,
        createdAt: true,
        updatedAt: true,
      },
      orderBy: { id: "asc" },
    }),
    client.studentLeave.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        examId: true,
        leaveType: true,
        reason: true,
        studyType: true,
        date: true,
        dateFrom: true,
        dateTo: true,
        notes: true,
        createdAt: true,
      },
      orderBy: { id: "asc" },
    }),
    client.opportunityLog.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        examId: true,
        action: true,
        amount: true,
        requestedAmount: true,
        appliedAmount: true,
        balanceBefore: true,
        balanceAfter: true,
        reversalOfLogId: true,
        ledgerVersion: true,
        settledGradeIds: true,
        reason: true,
        date: true,
        chapterId: true,
        chapterNameSnapshot: true,
      },
      orderBy: { id: "asc" },
    }),
    client.studentNote.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        kind: true,
        text: true,
        date: true,
        sourceType: true,
        sourceId: true,
        dismissalKey: true,
          dismissalReason: true,
        dismissalDate: true,
      },
      orderBy: { id: "asc" },
    }),
    // The academic engine currently reads every exam before filtering by the
    // student's course. Including every field keeps preview/save identical if
    // an exam is activated, rescheduled, reassigned, or its rules are edited.
    client.exam.findMany({
      select: {
        id: true,
        name: true,
        type: true,
        courseIds: true,
        examCourses: { select: { courseId: true, chapterId: true }, orderBy: { courseId: "asc" } },
        mainSite: true,
        date: true,
        fullMark: true,
        passMark: true,
        discountMark: true,
        opportunitiesPenalty: true,
        dismissalGrade: true,
        noDiscount: true,
        active: true,
        scheduledActivateAt: true,
      },
      orderBy: { id: "asc" },
    }),
    client.courseChapter.findMany({
      select: {
        id: true,
        courseId: true,
        chapterId: true,
        active: true,
        archived: true,
      },
      orderBy: { id: "asc" },
    }),
    client.chapter.findMany({
      select: { id: true, name: true, opportunities: true },
      orderBy: { id: "asc" },
    }),
    loadActiveGracePeriodsByStudent(client, [input.studentId]),
  ]);
  const gracePeriods = (gracePeriodsByStudent.get(input.studentId) || [])
    .map(({ id, startDate, endDate }) => ({ id, startDate, endDate }));

  const payload = {
    version: 8,
    student,
    gracePeriods,
    proposedCreatedAt: input.proposedCreatedAt ? dayKey(input.proposedCreatedAt) : "",
    proposedGracePeriods: input.proposedGracePeriods
      ? normalizeGracePeriodRanges(input.proposedGracePeriods)
          .map(({ startDate, endDate }) => ({ startDate, endDate }))
      : null,
    grades,
    leaves,
    opportunityLogs,
    studentNotes,
    exams,
    courseLinks,
    chapters,
  };
  return createHash("sha256").update(JSON.stringify(payload)).digest("hex");
}
