import { createHash } from "node:crypto";
import type { Prisma } from "@prisma/client";
import { db } from "@/lib/db";

type PrismaClientLike = typeof db | Prisma.TransactionClient;

function dayKey(value: Date | string): string {
  const date = value instanceof Date ? value : new Date(value);
  return Number.isFinite(date.getTime()) ? date.toISOString().slice(0, 10) : "";
}

/**
 * Fingerprints every database input read by the academic recalculation engine.
 * A save must present the token generated by its latest preview; any grade,
 * leave, note, exam, opportunity, chapter, or student-state change invalidates
 * that preview instead of silently applying a different result.
 */
export async function buildStudentAcademicImpactToken(
  client: PrismaClientLike,
  input: {
    studentId: string;
    proposedCreatedAt: Date | string;
    proposedGraceDays: number;
    proposedGraceStartDate?: Date | string | null;
  },
): Promise<string> {
  const student = await client.student.findUnique({
    where: { id: input.studentId },
    select: {
      id: true,
      courseId: true,
      status: true,
      opportunities: true,
      baseOpportunities: true,
      createdAt: true,
      accountingGraceDays: true,
      gracePeriodStartDate: true,
      dismissalType: true,
      dismissalReason: true,
      dismissalNotes: true,
    },
  });

  const [
    grades,
    leaves,
    opportunityLogs,
    studentNotes,
    exams,
    courseLinks,
    chapters,
  ] = await Promise.all([
    client.grade.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        examId: true,
        status: true,
        score: true,
        createdAt: true,
        updatedAt: true,
      },
      orderBy: { id: "asc" },
    }),
    client.studentLeave.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        examId: true,
        leaveType: true,
        reason: true,
        studyType: true,
        date: true,
        dateFrom: true,
        dateTo: true,
        notes: true,
        createdAt: true,
      },
      orderBy: { id: "asc" },
    }),
    client.opportunityLog.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        examId: true,
        action: true,
        amount: true,
        reason: true,
        date: true,
        chapterId: true,
        chapterNameSnapshot: true,
      },
      orderBy: { id: "asc" },
    }),
    client.studentNote.findMany({
      where: { studentId: input.studentId },
      select: {
        id: true,
        studentId: true,
        kind: true,
        text: true,
        date: true,
        sourceType: true,
        sourceId: true,
        dismissalKey: true,
        dismissalType: true,
        dismissalReason: true,
        dismissalDate: true,
      },
      orderBy: { id: "asc" },
    }),
    // The academic engine currently reads every exam before filtering by the
    // student's course. Including every field keeps preview/save identical if
    // an exam is activated, rescheduled, reassigned, or its rules are edited.
    client.exam.findMany({
      select: {
        id: true,
        name: true,
        type: true,
        courseIds: true,
        date: true,
        fullMark: true,
        passMark: true,
        discountMark: true,
        opportunitiesPenalty: true,
        dismissalGrade: true,
        noDiscount: true,
        active: true,
        scheduledActivateAt: true,
        scheduledDeactivateAt: true,
      },
      orderBy: { id: "asc" },
    }),
    client.courseChapter.findMany({
      select: {
        id: true,
        courseId: true,
        chapterId: true,
        active: true,
        archived: true,
      },
      orderBy: { id: "asc" },
    }),
    client.chapter.findMany({
      select: { id: true, name: true, opportunities: true },
      orderBy: { id: "asc" },
    }),
  ]);

  const payload = {
    version: 3,
    student,
    proposedCreatedAt: dayKey(input.proposedCreatedAt),
    proposedGraceStartDate: input.proposedGraceStartDate
      ? dayKey(input.proposedGraceStartDate)
      : "",
    proposedGraceDays: Math.min(
      30,
      Math.max(0, Math.trunc(Number(input.proposedGraceDays || 0))),
    ),
    grades,
    leaves,
    opportunityLogs,
    studentNotes,
    exams,
    courseLinks,
    chapters,
  };
  return createHash("sha256").update(JSON.stringify(payload)).digest("hex");
}
